project_id = "vlmdctanuarrmngkrvng"

[functions.quality-check]
verify_jwt = false

[functions.razorpay]
verify_jwt = false

[functions.process-messages]
verify_jwt = false

[functions.generate-seo]
verify_jwt = false

[functions.ai-generate]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.deploy-website]
verify_jwt = false

[functions.auto-release]
verify_jwt = false
