
ALTER TABLE build_requests
ADD COLUMN IF NOT EXISTS package_id TEXT DEFAULT 'basic',
ADD COLUMN IF NOT EXISTS package_price INTEGER DEFAULT 800,
ADD COLUMN IF NOT EXISTS coder_earning INTEGER DEFAULT 640,
ADD COLUMN IF NOT EXISTS website_purpose TEXT DEFAULT 'business',
ADD COLUMN IF NOT EXISTS reference_sites TEXT,
ADD COLUMN IF NOT EXISTS special_requirements TEXT,
ADD COLUMN IF NOT EXISTS practice_build BOOLEAN DEFAULT FALSE;

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS total_earned INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_sites_built INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_sites_live INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_passive INTEGER DEFAULT 0;
